"""nakarte-init — parse a nakarte URL and write a YAML config scaffold."""

import sys

import click
import yaml

from core.url_parser import extract_tracks, parse_nakarte_url


@click.command()
@click.option('--url', required=True, help='Full nakarte.me URL (copied from the browser).')
@click.option('--out', default='config.yaml', show_default=True, help='Output YAML path.')
@click.option('--scale', default=500, show_default=True, help='Scale as map metres per image cm (e.g. 500 means 500 m/cm = 1:50 000).')
@click.option('--dpi', default=300, show_default=True, help='Output resolution in DPI.')
@click.option('--paper', default='A4', show_default=True, help='Paper size: A4 or A3.')
@click.option('--orientation', default='portrait', show_default=True,
              help='Page orientation: portrait or landscape.')
def main(url, out, scale, dpi, paper, orientation):
    """Parse a nakarte URL and generate a raw YAML config scaffold."""
    try:
        url_params = parse_nakarte_url(url)
    except ValueError as e:
        click.echo(f'Error: {e}', err=True)
        sys.exit(1)

    if not url_params.get('nktk') and not url_params.get('nktl'):
        click.echo(
            'Error: URL contains no track data (no nktk= or nktl= parameter).\n'
            'Draw a route in nakarte.me and copy the URL from the address bar.',
            err=True,
        )
        sys.exit(1)

    click.echo('Reading track from URL...')
    try:
        tracks = extract_tracks(url_params)
    except PermissionError as e:
        click.echo(f'Error: {e}', err=True)
        sys.exit(1)
    except RuntimeError as e:
        click.echo(f'Error: {e}', err=True)
        sys.exit(1)

    if not tracks:
        click.echo('Error: no tracks found in URL.', err=True)
        sys.exit(1)

    if len(tracks) > 1:
        click.echo(
            f'Warning: {len(tracks)} tracks found in URL — '
            'only single-track URLs are fully supported. '
            'Using the first track; others will be ignored for marks.',
            err=True,
        )

    total_segs = sum(len(t.segments) for t in tracks)
    total_pts = sum(len(p) for t in tracks for p in t.segments)

    # Collect waypoints from all tracks as mark scaffold entries
    marks = []
    for track in tracks:
        for lat, lng, name in track.waypoints:
            marks.append({
                'lat': round(lat, 6),
                'lng': round(lng, 6),
                'name': name,
                'type': None,
            })

    config = {
        'map': {
            'url': url,
            # Optional explicit centre override: uncomment and set coordinates.
            # center: [lat, lng]
        },
        'export': {
            'paper': paper,
            'orientation': orientation,
            'scale': scale,
            'dpi': dpi,
        },
        'style': {
            'track_color': '#e60000',
            'track_width': 3,
        },
        'marks': marks,
    }

    header = (
        '# Generated by nakarte-init\n'
        '#\n'
        '# export.scale — map metres represented by 1 cm on the printed image.\n'
        '#   500  = 500 m/cm = 1:50 000   (default, suits 1:100 000 topo sheets)\n'
        '#   250  = 250 m/cm = 1:25 000\n'
        '#  1000  = 1 km/cm = 1:100 000\n'
        '#\n'
        '# export.paper       — A4 | A3\n'
        '# export.orientation — portrait | landscape\n'
        '# export.dpi   — print resolution (300 for standard print quality)\n'
        '#\n'
        '# Set `type` for each mark you want rendered. Leave null to skip.\n'
        '# Mark types: label | numbered_point | direction_arrow\n\n'
    )

    with open(out, 'w', encoding='utf-8') as f:
        f.write(header)
        yaml.dump(config, f, allow_unicode=True, default_flow_style=False, sort_keys=False)

    click.echo(f'Track:   {len(tracks)} track(s), {total_segs} segment(s), {total_pts} points')
    click.echo(f'Marks:   {len(marks)} waypoint(s) → config marks (type: null)')
    click.echo(f'Wrote {out}')


if __name__ == '__main__':
    main()
