"""nakarte-init — parse a nakarte GPX export and write a YAML config scaffold."""

import os
import sys

import click
import yaml

from core.gpx_parser import parse_gpx
from core.url_parser import parse_nakarte_url


@click.command()
@click.argument('gpx_file', type=click.Path(exists=True))
@click.option('--url', required=True, help='Full nakarte.me URL (copied from the browser).')
@click.option('--out', default='config.yaml', show_default=True, help='Output YAML path.')
@click.option('--width', default=2000, show_default=True, help='Output image width in pixels.')
@click.option('--height', default=1200, show_default=True, help='Output image height in pixels.')
def main(gpx_file, url, out, width, height):
    """Parse a nakarte GPX export and generate a raw YAML config scaffold."""
    try:
        parse_nakarte_url(url)
    except ValueError as e:
        click.echo(f'Error: {e}', err=True)
        sys.exit(1)

    try:
        gpx_data = parse_gpx(gpx_file)
    except Exception as e:
        click.echo(f'Error reading GPX: {e}', err=True)
        sys.exit(1)

    marks = [
        {'lat': round(wp.lat, 6), 'lng': round(wp.lng, 6), 'name': wp.name, 'type': None}
        for wp in gpx_data.waypoints
    ]

    config = {
        'map': {
            'url': url,
            'gpx': os.path.abspath(gpx_file),
            'width_px': width,
            'height_px': height,
        },
        'style': {
            'track_color': '#e60000',
            'track_width': 3,
        },
        'marks': marks,
    }

    header = (
        '# Generated by nakarte-init\n'
        '# Set `type` for each mark you want rendered. Leave null to skip.\n'
        '# Types: label | numbered_point | direction_arrow\n\n'
    )

    with open(out, 'w', encoding='utf-8') as f:
        f.write(header)
        yaml.dump(config, f, allow_unicode=True, default_flow_style=False, sort_keys=False)

    n_segs = len(gpx_data.tracks)
    n_pts = sum(len(s.points) for s in gpx_data.tracks)
    click.echo(f'Parsed {gpx_file}:')
    click.echo(f'  {len(gpx_data.waypoints)} waypoint(s) → marks (type: null)')
    click.echo(f'  {n_segs} track segment(s) with {n_pts} points')
    click.echo(f'Wrote {out}')


if __name__ == '__main__':
    main()
