"""nakarte-init — parse a nakarte URL and write a YAML config scaffold."""

import sys

import click
import yaml

from core.url_parser import extract_tracks, parse_nakarte_url


@click.command()
@click.option('--url', required=True, help='Full nakarte.me URL (copied from the browser).')
@click.option('--out', default='config.yaml', show_default=True, help='Output YAML path.')
@click.option('--width', default=2000, show_default=True, help='Output image width in pixels.')
@click.option('--height', default=1200, show_default=True, help='Output image height in pixels.')
def main(url, out, width, height):
    """Parse a nakarte URL and generate a raw YAML config scaffold."""
    try:
        url_params = parse_nakarte_url(url)
    except ValueError as e:
        click.echo(f'Error: {e}', err=True)
        sys.exit(1)

    if not url_params.get('nktk') and not url_params.get('nktl'):
        click.echo(
            'Error: URL contains no track data (no nktk= or nktl= parameter).\n'
            'Draw a route in nakarte.me and copy the URL from the address bar.',
            err=True,
        )
        sys.exit(1)

    click.echo('Reading track from URL...')
    try:
        tracks = extract_tracks(url_params)
    except PermissionError as e:
        click.echo(f'Error: {e}', err=True)
        sys.exit(1)
    except RuntimeError as e:
        click.echo(f'Error: {e}', err=True)
        sys.exit(1)

    if not tracks:
        click.echo('Error: no tracks found in URL.', err=True)
        sys.exit(1)

    if len(tracks) > 1:
        click.echo(
            f'Warning: {len(tracks)} tracks found in URL — '
            'only single-track URLs are fully supported. '
            'Using the first track; others will be ignored for marks.',
            err=True,
        )

    total_segs = sum(len(t.segments) for t in tracks)
    total_pts = sum(len(p) for t in tracks for p in t.segments)

    # Collect waypoints from all tracks as mark scaffold entries
    marks = []
    for track in tracks:
        for lat, lng, name in track.waypoints:
            marks.append({
                'lat': round(lat, 6),
                'lng': round(lng, 6),
                'name': name,
                'type': None,
            })

    config = {
        'map': {
            'url': url,
            'width_px': width,
            'height_px': height,
        },
        'style': {
            'track_color': '#e60000',
            'track_width': 3,
        },
        'marks': marks,
    }

    header = (
        '# Generated by nakarte-init\n'
        '# Set `type` for each mark you want rendered. Leave null to skip.\n'
        '# Types: label | numbered_point | direction_arrow\n\n'
    )

    with open(out, 'w', encoding='utf-8') as f:
        f.write(header)
        yaml.dump(config, f, allow_unicode=True, default_flow_style=False, sort_keys=False)

    click.echo(f'Track:   {len(tracks)} track(s), {total_segs} segment(s), {total_pts} points')
    click.echo(f'Marks:   {len(marks)} waypoint(s) → config marks (type: null)')
    click.echo(f'Wrote {out}')


if __name__ == '__main__':
    main()
